name: Monthly Stock Report

on:
  schedule:
    # Runs at 00:00 UTC on the last Thursday of every month
    - cron: '0 6 * * 4'  # Runs every Thursday
  workflow_dispatch: 
jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python app.py

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "Monthly Stock Report"
          body: "Please find attached the monthly stock analysis."
          to: "jyotipdas85@gmail.com"
          from: "jyotipdas85@outlook.com"
          attachments: "fno_analysis.xlsx"

