name: Monthly Stock Report

on:
  schedule:
    # Runs at 06:00 UTC (11:30 AM IST) on every Thursday
    - cron: '0 6 * * 4'
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          # python app.py
          python app_direct.py

      - name: "Debug: Show Directory Contents"
        run: |
          echo "📂 Current Directory: $(pwd)"
          ls -la

      - name: Verify File Exists
        run: |
          if [ -f "fno_analysis.xlsx" ]; then
            echo "✅ File generated successfully."
          else
            echo "❌ File NOT found!"
            exit 1
          fi
      - name: Commit and push Excel file
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Replace origin using the token correctly
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}

          git add fno_analysis.xlsx
          git diff --cached --quiet || git commit -m "Add/update fno_analysis.xlsx"
          git push origin HEAD:${{ github.ref_name }}