name: Monthly Stock Report

on:
  schedule:
    # Runs at 00:00 UTC on the last Thursday of every month
    - cron: '0 6 * * 4'  # Runs every Thursday
  workflow_dispatch: 
jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python app.py
      
      - name: Verify File Exists
        run: |
          if [ -f "fno_analysis.xlsx" ]; then
            echo "File generated successfully."
          else
            echo "File NOT found!"
            exit 1
          fi
      
      - name: Commit and Push Excel File to Repo
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add fno_analysis.xlsx
            git commit -m "Add latest stock analysis report"
            git push origin main  # Change 'main' to your repo’s default branch
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "Monthly Stock Report"
          body: "Please find attached the monthly stock analysis."
          to: "jyotipdas85@gmail.com"
          from: "jyotipdas85@outlook.com"
          attachments: "/home/runner/work/salary_trade/salary_trade/fno_analysis.xlsx"

