name: Monthly Stock Report

on:
  schedule:
    # Runs at 06:00 UTC (11:30 AM IST) on every Thursday
    - cron: '0 6 * * 4'
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          # python app.py
          python app_direct.py

      - name: "Debug: Show Directory Contents"
        run: |
          echo "📂 Current Directory: $(pwd)"
          ls -la

      - name: Verify File Exists
        run: |
          if [ -f "fno_analysis.xlsx" ]; then
            echo "✅ File generated successfully."
          else
            echo "❌ File NOT found!"
            exit 1
          fi
      - name: copy the file
        run: |
             git config --global user.name "github-actions"
             git config --global user.email "github-actions@github.com"
             git add fno_analysis.xlsx
             git commit -m "Add/update fno_analysis.xlsx" ||             echo "No changes to commit"
             git push

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "Monthly Stock Report"
          body: "Please find attached the monthly stock analysis."
          to: "jyotipdas85@gmail.com"
          from: "jyotipdas85@gmail.com"
          attachments: "fno_analysis.xlsx"
